blank_issues_enabled: false
contact_links:
  - name: ğŸ’¡ Profile ç¤ºä¾‹
    url: https://github.com/RAKWireless/RAK-BACnet-Profiles/tree/main/examples
    about: æŸ¥çœ‹æ ‡å‡† Profile ç¤ºä¾‹å’Œæµ‹è¯•æ•°æ®
