blank_issues_enabled: false
contact_links:
  - name: ðŸ’¡ Profile Examples
    url: https://github.com/RAKWireless/RAK-BACnet-Profiles/tree/main/examples
    about: View standard profile examples and test data
